from django.urls import path

from .views import (
    ChatAdminOverviewView,
    ChatConfigView,
    ConversationAcceptView,
    ConversationListView,
    ConversationMessagesView,
    ConversationStateView,
    FriendsListView,
    MessageEditDeleteView,
    MessageUploadView,
    PresencePingView,
    RoomListCreateView,
    RoomDetailView,
    RoomLeaveView,
    RoomMembersView,
    RoomMessagesView,
    RoomStagePresenceView,
    RoomTypingView,
    RoomUploadView,
    PromptRoomListCreateView,
    RoomRecapView,
    RoomMessageEditDeleteView,
    RoomMessagePinView,
    RoomMessageReactView,
    SendMessageView,
    MessagePinView,
    MessageReactView,
    SharedSpaceView,
    StartConversationView,
    TypingView,
    ConversationScheduleView,
    RoomScheduleView,
    ScheduledMessageCancelView,
    ScheduledMessageListView,
)

urlpatterns = [
    path('config/', ChatConfigView.as_view(), name='chat-config'),
    path('admin/overview/', ChatAdminOverviewView.as_view(), name='chat-admin-overview'),
    path('friends/', FriendsListView.as_view(), name='chat-friends'),
    path('presence/', PresencePingView.as_view(), name='chat-presence'),
    path('conversations/', ConversationListView.as_view(), name='chat-conversations'),
    path(
        'conversations/start/',
        StartConversationView.as_view(),
        name='chat-start',
    ),
    path('send/', SendMessageView.as_view(), name='chat-send'),
    path(
        'conversations/<int:conversation_id>/state/',
        ConversationStateView.as_view(),
        name='chat-conversation-state',
    ),
    path(
        'conversations/<int:conversation_id>/accept/',
        ConversationAcceptView.as_view(),
        name='chat-conversation-accept',
    ),
    path(
        'conversations/<int:conversation_id>/messages/',
        ConversationMessagesView.as_view(),
        name='chat-messages',
    ),
    path(
        'conversations/<int:conversation_id>/typing/',
        TypingView.as_view(),
        name='chat-typing',
    ),
    path(
        'conversations/<int:conversation_id>/upload/',
        MessageUploadView.as_view(),
        name='chat-upload',
    ),
    path(
        'conversations/<int:conversation_id>/schedule/',
        ConversationScheduleView.as_view(),
        name='chat-conversation-schedule',
    ),
    path('rooms/', RoomListCreateView.as_view(), name='chat-rooms'),
    path('prompt-rooms/', PromptRoomListCreateView.as_view(), name='chat-prompt-rooms'),
    path('rooms/<int:room_id>/', RoomDetailView.as_view(), name='chat-room-detail'),
    path('rooms/<int:room_id>/members/', RoomMembersView.as_view(), name='chat-room-members'),
    path('rooms/<int:room_id>/leave/', RoomLeaveView.as_view(), name='chat-room-leave'),
    path('rooms/<int:room_id>/stage/', RoomStagePresenceView.as_view(), name='chat-room-stage'),
    path(
        'rooms/<int:room_id>/messages/',
        RoomMessagesView.as_view(),
        name='chat-room-messages',
    ),
    path(
        'rooms/<int:room_id>/typing/',
        RoomTypingView.as_view(),
        name='chat-room-typing',
    ),
    path(
        'rooms/<int:room_id>/upload/',
        RoomUploadView.as_view(),
        name='chat-room-upload',
    ),
    path(
        'rooms/<int:room_id>/recap/',
        RoomRecapView.as_view(),
        name='chat-room-recap',
    ),
    path(
        'rooms/<int:room_id>/schedule/',
        RoomScheduleView.as_view(),
        name='chat-room-schedule',
    ),
    path('scheduled/', ScheduledMessageListView.as_view(), name='chat-scheduled-list'),
    path('scheduled/<int:scheduled_id>/', ScheduledMessageCancelView.as_view(), name='chat-scheduled-cancel'),
    path('shared_space/', SharedSpaceView.as_view(), name='chat-shared-space'),
    path('messages/<int:message_id>/', MessageEditDeleteView.as_view(), name='chat-message-edit-delete'),
    path('messages/<int:message_id>/pin/', MessagePinView.as_view(), name='chat-message-pin'),
    path('messages/<int:message_id>/react/', MessageReactView.as_view(), name='chat-message-react'),
    path('room-messages/<int:message_id>/', RoomMessageEditDeleteView.as_view(), name='chat-room-message-edit-delete'),
    path('room-messages/<int:message_id>/pin/', RoomMessagePinView.as_view(), name='chat-room-message-pin'),
    path('room-messages/<int:message_id>/react/', RoomMessageReactView.as_view(), name='chat-room-message-react'),
]
