# Generated by Django 5.2.2 on 2026-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_type_alter_notification_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follow', 'Follow'), ('shop_purchase', 'Shop Purchase'), ('challenge_complete', 'Challenge Complete'), ('moderation_action', 'Moderation Action'), ('chat_message', 'Chat Message'), ('achievement_unlocked', 'Achievement Unlocked')], max_length=20),
        ),
    ]
