# Generated by Django 5.2.2 on 2026-07-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follow', 'Follow'), ('shop_purchase', 'Shop Purchase'), ('challenge_complete', 'Challenge Complete'), ('moderation_action', 'Moderation Action'), ('chat_message', 'Chat Message'), ('achievement_unlocked', 'Achievement Unlocked'), ('mention', 'Mention')], max_length=20),
        ),
    ]
