# Generated by Django 6.0.5 on 2026-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_push_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follow', 'Follow'), ('shop_purchase', 'Shop Purchase'), ('challenge_complete', 'Challenge Complete'), ('moderation_action', 'Moderation Action'), ('chat_message', 'Chat Message'), ('achievement_unlocked', 'Achievement Unlocked'), ('mention', 'Mention'), ('share', 'Share')], max_length=20),
        ),
    ]
