# Generated by Django 6.0.5 on 2026-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follow', 'Follow'), ('shop_purchase', 'Shop Purchase'), ('challenge_complete', 'Challenge Complete'), ('moderation_action', 'Moderation Action'), ('chat_message', 'Chat Message'), ('achievement_unlocked', 'Achievement Unlocked'), ('mention', 'Mention'), ('share', 'Share'), ('idea_pledge', 'Idea Pledge'), ('idea_comment', 'Idea Comment'), ('idea_apply', 'Idea Apply'), ('idea_accepted', 'Idea Accepted'), ('idea_rejected', 'Idea Rejected'), ('tip', 'Tip')], max_length=20),
        ),
    ]
