# Generated by Django 5.2.2 on 2026-07-18 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_notification_verb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('likes', models.BooleanField(default=True)),
                ('comments', models.BooleanField(default=True)),
                ('follows', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('shares', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('tips', models.BooleanField(default=True)),
                ('story_reactions', models.BooleanField(default=True)),
                ('new_follower', models.BooleanField(default=True)),
                ('verified_badge', models.BooleanField(default=True)),
                ('challenge_complete', models.BooleanField(default=True)),
                ('shop_updates', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='09:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
