# Generated by Django 5.2.16 on 2026-08-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_forge_studio_followup'),
        ('studio', '0002_canvasmedia_filter_drawsession_mode_canvasshape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='studio_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.drawsession'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('follow', 'Follow'), ('shop_purchase', 'Shop Purchase'), ('challenge_complete', 'Challenge Complete'), ('moderation_action', 'Moderation Action'), ('chat_message', 'Chat Message'), ('achievement_unlocked', 'Achievement Unlocked'), ('mention', 'Mention'), ('share', 'Share'), ('idea_pledge', 'Idea Pledge'), ('idea_comment', 'Idea Comment'), ('idea_apply', 'Idea Apply'), ('idea_accepted', 'Idea Accepted'), ('idea_rejected', 'Idea Rejected'), ('tip', 'Tip'), ('going_live', 'Going Live'), ('forge_invite', 'Forge Invite'), ('forge_pending', 'Forge Pending'), ('forge_approved', 'Forge Approved'), ('forge_rejected', 'Forge Rejected'), ('studio_invite', 'Studio Invite')], max_length=20),
        ),
    ]
