# Generated by Django 5.2.2 on 2026-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_flagged_reel_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedcontent',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('reel', 'Reel'), ('reel_comment', 'Reel comment'), ('story', 'Story')], max_length=20),
        ),
    ]
