# Generated by Django 5.2.2 on 2026-07-18 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_social_safety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedcontent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='ai_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='ai_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='ai_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='ai_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_flagged', 'Auto-flagged by AI')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('reel', 'Reel'), ('reel_comment', 'Reel comment'), ('story', 'Story'), ('live_chat', 'Live chat message')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['type', 'object_id'], name='moderation__type_b76b99_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['status', 'ai_flagged'], name='moderation__status_ba287c_idx'),
        ),
    ]
