# Generated by Django 5.2.2 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_alter_flaggedcontent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('reel', 'Reel'), ('reel_comment', 'Reel comment'), ('story', 'Story'), ('live_chat', 'Live chat message')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff_note', models.TextField(blank=True, default='')),
                ('flagged_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='moderation.flaggedcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='moderation__user_id_8a1f2c_idx'),
                    models.Index(fields=['content_type', 'object_id'], name='moderation__content_4b9e1a_idx'),
                ],
            },
        ),
    ]
