# Generated by Django 5.2.2 on 2026-08-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0010_contentappeal_bottle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentappeal',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('reel', 'Reel'), ('reel_comment', 'Reel comment'), ('story', 'Story'), ('live_chat', 'Live chat message'), ('chat_message', 'Direct chat message'), ('room_message', 'Room chat message'), ('bottle', 'Emotion bottle'), ('idea', 'Bazaar idea')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('reel', 'Reel'), ('reel_comment', 'Reel comment'), ('story', 'Story'), ('live_chat', 'Live chat message'), ('chat_message', 'Direct chat message'), ('room_message', 'Room chat message'), ('bottle', 'Emotion bottle'), ('idea', 'Bazaar idea')], db_index=True, max_length=20),
        ),
    ]
