# Generated by Django 6.0.5 on 2026-06-24 17:18

import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/', validators=[outverse.upload_validators.validate_generic_upload]),
        ),
        migrations.AlterField(
            model_name='roommessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/room_attachments/', validators=[outverse.upload_validators.validate_generic_upload]),
        ),
    ]
