# Generated by Django 6.0.5 on 2026-07-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversationuserstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationuserstate',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
