# Generated by Django 6.0.5 on 2026-07-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_roomreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
