# Generated by Django 5.2.2 on 2026-07-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('nova', 'Nova'), ('supernova', 'Supernova'), ('galaxy', 'Galaxy')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_usd_cents', models.PositiveIntegerField(help_text='Monthly price in USD cents, e.g. 999 = $9.99')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Set once the plan exists in the Stripe dashboard', max_length=100)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_recommended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price_usd_cents'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past due')], db_index=True, default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
