# Generated by Django 6.0.5 on 2026-07-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_creatortier_creatorsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSubscriptionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=120, unique=True)),
                ('amount_usd_cents', models.PositiveIntegerField()),
                ('coins_credited', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='subscriptions.creatorsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
