from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    CreatorSuggestionsView,
    ExperienceDetailView,
    ExperienceListCreateView,
    FollowView,
    ForgotPasswordView,
    LoginView,
    LogoutView,
    MeView,
    PassportsView,
    PublicExperienceView,
    PublicPassportsView,
    OnboardingOptionsView,
    ProfileViewSet,
    PromoteStaffView,
    RegisterView,
    ToggleShadowBanView,
    ResetPasswordView,
    UserByUsernameView,
    UserFollowersView,
    UserFollowingView,
    UserMentionSearchView,
    UserProfileUpdateView,
    UserProfileView,
    UserSocialListView,
    UserSocialView,
    UsernameAvailabilityView,
    VerifyEmailView,
    YearInView,
)
from .account_views import (
    AccountDeactivateView,
    AccountDeleteView,
    AccountExportView,
    AdminVerificationReviewView,
    GoogleAuthView,
    AppleAuthView,
    TwoFactorLoginView,
    TwoFactorSetupView,
    VerificationRequestView,
)

router = DefaultRouter()
router.register(r'profiles', ProfileViewSet)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('login/2fa/', TwoFactorLoginView.as_view(), name='login-2fa'),
    path('auth/google/', GoogleAuthView.as_view(), name='auth-google'),
    path('auth/apple/', AppleAuthView.as_view(), name='auth-apple'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify-email'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('check-username/', UsernameAvailabilityView.as_view(), name='check-username'),
    path('by-username/<str:username>/', UserByUsernameView.as_view(), name='user-by-username'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('me/experience/', ExperienceListCreateView.as_view(), name='me-experience'),
    path('me/experience/<int:experience_id>/', ExperienceDetailView.as_view(), name='me-experience-detail'),
    path('me/', MeView.as_view(), name='me'),
    path('me/passports/', PassportsView.as_view(), name='me-passports'),
    path('me/export/', AccountExportView.as_view(), name='me-export'),
    path('me/deactivate/', AccountDeactivateView.as_view(), name='me-deactivate'),
    path('me/delete/', AccountDeleteView.as_view(), name='me-delete'),
    path('me/2fa/', TwoFactorSetupView.as_view(), name='me-2fa'),
    path('me/verification/', VerificationRequestView.as_view(), name='me-verification'),
    path('admin/verification/', AdminVerificationReviewView.as_view(), name='admin-verification-list'),
    path('admin/verification/<int:request_id>/', AdminVerificationReviewView.as_view(), name='admin-verification-review'),
    path('me/year/', YearInView.as_view(), name='me-year'),
    path('onboarding-options/', OnboardingOptionsView.as_view(), name='onboarding-options'),
    path('suggestions/', CreatorSuggestionsView.as_view(), name='suggestions'),
    path('mentions/', UserMentionSearchView.as_view(), name='user-mentions'),
    path('follow/', FollowView.as_view(), name='follow'),
    path('social/', UserSocialView.as_view(), name='user-social'),
    path('social/lists/', UserSocialListView.as_view(), name='user-social-lists'),
    path('<int:user_id>/experience/', PublicExperienceView.as_view(), name='user-experience'),
    path('<int:user_id>/passports/', PublicPassportsView.as_view(), name='user-passports'),
    path('<int:user_id>/promote/', PromoteStaffView.as_view(), name='user-promote-staff'),
    path('<int:user_id>/shadow-ban/', ToggleShadowBanView.as_view(), name='user-shadow-ban'),
    path('<int:user_id>/followers/', UserFollowersView.as_view(), name='user-followers'),
    path('<int:user_id>/following/', UserFollowingView.as_view(), name='user-following'),
    path('<int:user_id>/update/', UserProfileUpdateView.as_view(), name='user-profile-update'),
    path('<int:user_id>/', UserProfileView.as_view(), name='user-profile'),
    path('', include(router.urls)),
]
