# Generated by Django 6.0.5 on 2026-06-24 17:18

import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_madness_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_items/', validators=[outverse.upload_validators.validate_image_upload]),
        ),
    ]
