# Generated by Django 5.2.2 on 2026-07-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], db_index=True, default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
