# Generated by Django 5.2.2 on 2026-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_coinpack_coinpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited stock', null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('idea', 'Idea')], db_index=True, default='digital', max_length=20),
        ),
    ]
