# Generated by Django 5.2.2 on 2026-08-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopitem_stock_alter_shopitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='idea_kind',
            field=models.CharField(blank=True, choices=[('', 'Plain idea'), ('cursed_prompt', 'Cursed Prompt'), ('alternate_you', 'Alternate You'), ('blind_drop', 'Blind Drop'), ('constellation_pack', 'Constellation Pack'), ('bottle', 'Idea in a Bottle'), ('reverse_commission', 'Reverse Commission')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='unlock_at',
            field=models.DateTimeField(blank=True, help_text="Only used when idea_kind='bottle' — content stays hidden until this time", null=True),
        ),
    ]
