# Generated by Django 6.0.5 on 2026-07-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(db_index=True, max_length=10)),
                ('content_id', models.PositiveIntegerField(db_index=True)),
                ('author_id', models.PositiveIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('dwell_3s', 'Dwell 3s'), ('dwell_10s', 'Dwell 10s'), ('like', 'Reaction'), ('comment', 'Comment'), ('share', 'Share'), ('save', 'Save'), ('repost', 'Repost'), ('hide', 'Hide')], db_index=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'author_id', '-created_at'], name='analytics_c_user_id_2b7fb2_idx'), models.Index(fields=['content_type', 'content_id'], name='analytics_c_content_d7b39f_idx')],
            },
        ),
    ]
