# Generated by Django 6.0.5 on 2026-06-24 17:18

import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_comment_reactions_music_trim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='custom_audio',
            field=models.FileField(blank=True, null=True, upload_to='reels/audio/', validators=[outverse.upload_validators.validate_audio_upload]),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(upload_to='reels/', validators=[outverse.upload_validators.validate_video_upload]),
        ),
        migrations.AlterField(
            model_name='reelmusictrack',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='reels/music/', validators=[outverse.upload_validators.validate_audio_upload]),
        ),
    ]
