# Generated by Django 5.2.2 on 2026-07-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0006_savedreel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reelcomment',
            options={'ordering': ['-is_pinned', 'created_at']},
        ),
        migrations.AddField(
            model_name='reel',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reelcomment',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
