# Generated by Django 6.0.5 on 2026-07-07 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0008_reelcomment_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, default='')),
                ('mood', models.CharField(blank=True, default='cosmic', max_length=20)),
                ('filter_style', models.CharField(blank=True, default='none', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sound_label', models.CharField(blank=True, default='', max_length=120)),
                ('music_start_seconds', models.FloatField(default=0)),
                ('music_end_seconds', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='reels.reelmusictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
