# Generated by Django 6.0.5 on 2026-07-08 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0009_reel_drafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('copy', 'Copy link'), ('native', 'Native share'), ('twitter', 'X / Twitter'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('reddit', 'Reddit'), ('bluesky', 'Bluesky'), ('email', 'Email'), ('dm', 'Direct message'), ('story', 'Share to story'), ('embed', 'Embed'), ('card', 'Share card'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='reels.reel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reel_share_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reel', 'channel'], name='reels_reels_reel_id_b10a8e_idx'), models.Index(fields=['reel', 'user'], name='reels_reels_reel_id_4d997d_idx')],
            },
        ),
    ]
