# Generated by Django 6.0.5 on 2026-07-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0011_reellike_type'),
        ('subscriptions', '0003_creatorsubscriptionpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='required_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_reels', to='subscriptions.creatortier'),
        ),
        migrations.AddField(
            model_name='reel',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('subscribers', 'Subscribers')], db_index=True, default='public', max_length=12),
        ),
    ]
