# Generated by Django 5.2.2 on 2026-07-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0012_reel_required_tier_reel_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='remix_of',
            field=models.ForeignKey(blank=True, help_text='Original reel this is a remix of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='reels.reel'),
        ),
        migrations.AddField(
            model_name='reel',
            name='stitch_of',
            field=models.ForeignKey(blank=True, help_text='Original reel this is a stitch of (beginning segment used)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stitches', to='reels.reel'),
        ),
    ]
