# Generated by Django 5.2.16 on 2026-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0014_livesession_livereaction_livechatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='provider_input_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='livesession',
            name='webrtc_publish_url',
            field=models.URLField(blank=True),
        ),
    ]
