# Generated by Django 5.2.2 on 2026-07-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_submissions(apps, schema_editor):
    Submission = apps.get_model('challenges', 'Submission')
    seen = set()
    for sub in Submission.objects.order_by('-submitted_at', '-id').iterator():
        key = (sub.user_id, sub.challenge_id)
        if key in seen:
            sub.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_lab_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_challenges',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(dedupe_submissions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(
                fields=('user', 'challenge'),
                name='unique_submission_per_user_challenge',
            ),
        ),
    ]
