# Generated by Django 5.2.16 on 2026-08-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasmedia',
            name='filter',
            field=models.CharField(blank=True, default='', help_text='CSS filter() string, e.g. "brightness(1.1) contrast(1.05)"', max_length=200),
        ),
        migrations.AddField(
            model_name='drawsession',
            name='mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('live', 'Live')], db_index=True, default='solo', max_length=10),
        ),
        migrations.CreateModel(
            name='CanvasShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('line', 'Line')], max_length=10)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=120)),
                ('height', models.FloatField(default=120)),
                ('rotation', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('color', models.CharField(default='#5B21B6', max_length=20)),
                ('stroke_width', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='studio.drawsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_shapes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='studio.drawsession')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
