# Generated by Django 5.2.16 on 2026-08-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_canvasmedia_filter_drawsession_mode_canvasshape_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Text', max_length=300)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=200)),
                ('height', models.FloatField(default=60)),
                ('rotation', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('color', models.CharField(default='#5B21B6', max_length=20)),
                ('font_size', models.PositiveSmallIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='studio.drawsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_texts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
    ]
