# Generated by Django 5.2.16 on 2026-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_canvastext'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasmedia',
            name='opacity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='canvasmedia',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canvasshape',
            name='opacity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='canvasshape',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canvastext',
            name='opacity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='canvastext',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
