# Generated by Django 5.2.16 on 2026-08-05 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='content_rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_prompt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='story',
            name='pov',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='story',
            name='require_approval',
            field=models.BooleanField(default=False, help_text='When true, new segments need owner approval before readers see them.'),
        ),
        migrations.AddField(
            model_name='story',
            name='target_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='tone',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='story',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('invite_only', 'Invite only')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='max_segments',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='SegmentDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_dialogues', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='narratives.segmentdialogue')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='narratives.segment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('editor', 'Editor'), ('narrator', 'Narrator')], default='writer', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='narratives.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('story', 'user')},
            },
        ),
    ]
