# Generated by Django 5.2.16 on 2026-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0002_forge_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
