# Generated by Django 5.2.16 on 2026-08-05 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0003_forge_studio_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='characters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='outline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='studio_mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('collab', 'Collaborative')], default='solo', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='world_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='writing_goal',
            field=models.PositiveIntegerField(blank=True, help_text='Optional total word goal for the story.', null=True),
        ),
        migrations.CreateModel(
            name='SegmentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='narratives.segment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='narratives.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_forge_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'story')},
            },
        ),
    ]
