# Generated by Django 5.2.2 on 2026-06-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postreaction'),
        ('posts', '0010_comment_text_blank'),
    ]

    operations = [
    ]
