# Generated by Django 6.0.5 on 2026-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boost_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_boosted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
