# Generated by Django 6.0.5 on 2026-07-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_post_boost_expires_at_post_is_boosted'),
        ('reels', '0011_reellike_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_to_posts', to='reels.reel'),
        ),
    ]
