# Generated by Django 6.0.5 on 2026-07-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_post_shared_reel'),
        ('subscriptions', '0003_creatorsubscriptionpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='required_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_posts', to='subscriptions.creatortier'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('subscribers', 'Subscribers')], db_index=True, default='public', max_length=12),
        ),
    ]
