# Generated by Django 6.0.5 on 2026-06-24 17:18

import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', validators=[outverse.upload_validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/', validators=[outverse.upload_validators.validate_video_upload]),
        ),
    ]
