# Generated by Django 5.2.2 on 2026-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_expires_at_storyreaction_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='background_style',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='story',
            name='drawing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='filter_style',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('cosmic', 'Cosmic Glow'), ('glitch', 'Glitch'), ('vintage', 'Vintage'), ('neon', 'Neon'), ('void', 'Void'), ('dream', 'Dream'), ('pulse', 'Pulse')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='overlays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
