# Generated by Django 5.2.2 on 2026-07-18 13:05

import django.db.models.deletion
import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_storyreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyconstellation',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='constellations/covers/', validators=[outverse.upload_validators.validate_image_upload]),
        ),
        migrations.CreateModel(
            name='StoryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='stories.storyconstellation')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_entries', to='stories.story')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('constellation', 'story')},
            },
        ),
    ]
