# Generated by Django 5.2.2 on 2026-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='message_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='weirdness_level',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
