# Generated by Django 6.0.5 on 2026-07-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_userpreferences_message_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='comment_policy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('following', 'People you follow'), ('none', 'No one')], default='everyone', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='dm_policy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('following', 'People you follow'), ('none', 'No one')], default='everyone', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='hidden_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='mention_policy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('following', 'People you follow'), ('none', 'No one')], default='everyone', max_length=16),
        ),
    ]
