# Generated by Django 5.2.2 on 2026-07-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_social_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='tag_policy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('following', 'People you follow'), ('none', 'No one')], default='everyone', max_length=16),
        ),
    ]
