# Generated by Django 6.0.5 on 2026-07-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_userpreferences_quiet_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='read_receipts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
