# Generated by Django 5.2.2 on 2026-07-02 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('template', 'Template'), ('toolkit', 'Toolkit'), ('tutorial', 'Tutorial')], db_index=True, default='template', max_length=20)),
                ('mood', models.CharField(blank=True, choices=[('inspiration', 'Creative Inspiration'), ('productivity', 'Productivity Boost'), ('learning', 'Learning Path'), ('quick', 'Quick Solutions')], max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('file_size_label', models.CharField(blank=True, help_text='e.g. "1.2 MB"', max_length=32)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-download_count', '-created_at'],
            },
        ),
    ]
