# Generated by Django 5.2.2 on 2026-08-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speculative', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrawSession',
        ),
    ]
