# Generated by Django 5.2.16 on 2026-08-18 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speculative', '0002_delete_drawsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='failedidea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_failed_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FailedIdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='speculative.failedidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_idea_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
