# Generated by Django 5.2.16 on 2026-08-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speculative', '0003_failedidea_likes_failedideacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='character',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(default=True, help_text="Private characters only appear in their creator's collection."),
        ),
    ]
