# Generated by Django 5.2.2 on 2026-07-18 20:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('objective', models.CharField(choices=[('awareness', 'Brand Awareness'), ('traffic', 'Traffic / Clicks'), ('engagement', 'Engagement'), ('conversions', 'Conversions'), ('app_installs', 'App Installs')], default='traffic', max_length=20)),
                ('bid_strategy', models.CharField(choices=[('cpm', 'CPM — Cost per 1,000 Impressions'), ('cpc', 'CPC — Cost per Click'), ('cpa', 'CPA — Cost per Action')], default='cpm', max_length=10)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lifetime_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('targeting', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('disapproved', 'Disapproved')], db_index=True, default='draft', max_length=20)),
                ('targeting_override', models.JSONField(blank=True, default=dict)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('referrer_url', models.URLField(blank=True, max_length=500)),
                ('landing_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='ads.ad')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.adcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase', 'Purchase'), ('signup', 'Sign Up'), ('lead', 'Lead'), ('add_to_cart', 'Add to Cart'), ('initiate_checkout', 'Initiate Checkout'), ('custom', 'Custom Event')], max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('attributed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='ads.ad')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='ads.adcampaign')),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='ads.adclick')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attributed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('image', 'Single Image'), ('carousel', 'Carousel (2-10 images)'), ('video', 'Video'), ('story', 'Full-screen Story'), ('reel', 'Reel-style Video')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('aspect_ratio', models.CharField(default='1:1', max_length=10)),
                ('headline', models.CharField(blank=True, max_length=125)),
                ('primary_text', models.TextField(blank=True, max_length=2000)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('cta_text', models.CharField(blank=True, max_length=30)),
                ('landing_url', models.URLField(max_length=500)),
                ('utm_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.adcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adcreative'),
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('placement', models.CharField(db_index=True, max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('os', models.CharField(blank=True, max_length=30)),
                ('browser', models.CharField(blank=True, max_length=30)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('bid_price', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='ads.ad')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.adcampaign')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.adcreative')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adclick',
            name='impression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.adimpression'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['advertiser', 'status'], name='ads_adcampa_adverti_d7f2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='ads_adcampa_status_60ee9d_idx'),
        ),
        migrations.AddIndex(
            model_name='adconversion',
            index=models.Index(fields=['ad', 'attributed_at'], name='ads_adconve_ad_id_599584_idx'),
        ),
        migrations.AddIndex(
            model_name='adconversion',
            index=models.Index(fields=['campaign', 'attributed_at'], name='ads_adconve_campaig_1549f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['campaign', 'status'], name='ads_ad_campaig_c035bb_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'created_at'], name='ads_adimpre_ad_id_e3dcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['campaign', 'created_at'], name='ads_adimpre_campaig_ed4b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', 'created_at'], name='ads_adimpre_user_id_20e7db_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['placement', 'created_at'], name='ads_adimpre_placeme_4388e2_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['ad', 'created_at'], name='ads_adclick_ad_id_cff191_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['campaign', 'created_at'], name='ads_adclick_campaig_448140_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['impression', 'created_at'], name='ads_adclick_impress_d67053_idx'),
        ),
    ]
