# Generated by Django 6.0.5 on 2026-06-24 17:18

import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_points_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[outverse.upload_validators.validate_image_upload]),
        ),
    ]
