# Generated by Django 6.0.5 on 2026-06-24 18:32

import outverse.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_interests_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/', validators=[outverse.upload_validators.validate_image_upload]),
        ),
    ]
