# Generated by Django 6.0.5 on 2026-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_account_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
