# Generated by Django 6.0.5 on 2026-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_badge_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spender_tier',
            field=models.CharField(choices=[('none', 'None'), ('bronze', 'Bronze Patron'), ('silver', 'Silver Patron'), ('gold', 'Gold Patron')], db_index=True, default='none', max_length=10),
        ),
    ]
