# Generated by Django 5.2.16 on 2026-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_gdprexportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shadow_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
