# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_shadow_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauthaccount',
            name='provider',
            field=models.CharField(
                choices=[('google', 'Google'), ('apple', 'Apple')],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
