# Generated by Django 6.0.5 on 2026-07-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_privacy_communitymembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='flair',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
