"""
Django settings for outverse project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file() -> None:
    """Load .env files: repo root first, then backend/ overrides for local dev."""
    layers = (
        (BASE_DIR.parent / '.env', False),
        (BASE_DIR / '.env', True),
    )
    for env_path, override in layers:
        if not env_path.is_file():
            continue
        for line in env_path.read_text(encoding='utf-8').splitlines():
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            key, _, value = line.partition('=')
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if not key:
                continue
            if override or key not in os.environ:
                os.environ[key] = value


_load_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'users.apps.UsersConfig',
    'challenges',
    'ideas',
    'moods',
    'bottles',
    'stories',
    'reels',
    'narratives',
    'shop',
    'moderation',
    'analytics',
    'audit',
    'posts',
    'notifications',
    'chat',
    'capsules',
    'preferences',
    'channels',
    'questions',
    'resources',
    'collab',
    'subscriptions',
    'speculative',
    'studio',
    'saved',
    'notes',
    'communities',
    'ads.apps.AdsConfig',
    'storages',
]

ASGI_APPLICATION = 'outverse.asgi.application'

CHAT_ALLOW_LEGACY_USER_ID = False

_redis_url = os.environ.get('REDIS_URL', '').strip()
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_redis_url],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'outverse.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---- Sentry (env-gated; no-op without SENTRY_DSN) ----
SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.redis import RedisIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=os.environ.get('SENTRY_ENV', 'production'),
            release=os.environ.get('SENTRY_RELEASE', None),
            send_default_pii=False,
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0')),
            integrations=[
                DjangoIntegration(transaction_style='url'),
                RedisIntegration(),
            ],
        )
    except Exception:  # noqa: BLE001 — never let telemetry break boot.
        pass

ROOT_URLCONF = 'outverse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'outverse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _database_from_url(url: str) -> dict:
    """Parse postgres://user:pass@host:port/dbname into a Django DATABASES entry."""
    from urllib.parse import unquote, urlparse

    parsed = urlparse(url.strip())
    if parsed.scheme not in ('postgres', 'postgresql'):
        raise ValueError(f'Unsupported database URL scheme: {parsed.scheme}')
    return {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': parsed.path.lstrip('/'),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or 'localhost',
        'PORT': str(parsed.port or 5432),
    }


_pg_host = os.environ.get('POSTGRES_HOST', 'localhost')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB', 'outverse_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': _pg_host,
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        # Managed hosts (RDS, etc.) require/expect SSL; local dev Postgres usually doesn't have it configured.
        'OPTIONS': {'sslmode': 'require'} if _pg_host not in ('localhost', '127.0.0.1') else {},
    }
}

_replica_url = os.environ.get('DATABASE_REPLICA_URL', '').strip()
if _replica_url:
    DATABASES['replica'] = _database_from_url(_replica_url)
    DATABASE_ROUTERS = ['outverse.db_router.PrimaryReplicaRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _cors_origins.strip():
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in _cors_origins.split(',') if o.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = []

# Allow the dashboard (served from a "public" origin like localhost) to reach
# this server even when the browser classifies it as a private-network target
# (Chrome's Private Network Access checks), so local/dev cross-origin API
# calls aren't silently blocked after a successful preflight.
CORS_ALLOW_PRIVATE_NETWORK = True
# Frontend sends `credentials: 'include'` on every API call — without this
# header browsers block the response and JS sees "Failed to fetch".
CORS_ALLOW_CREDENTIALS = True

# ربط النظام بنموذج المستخدم المخصص
AUTH_USER_MODEL = 'users.User'

# إضافة إعدادات REST Framework
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'outverse.authentication.SoftTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.environ.get('DRF_PAGE_SIZE', '20')),
    # Rates for the scoped throttle classes in outverse/throttles.py — every
    # scope referenced there must have an entry or the throttle crashes the
    # request with ImproperlyConfigured instead of just rate-limiting it.
    'DEFAULT_THROTTLE_RATES': {
        'burst': '200/min',
        'sustained': '1000/hour',
        'auth.login': '30/5min',
        'auth.register': '5/hour',
        'auth.forgot_password': '3/hour',
        'auth.reset_password': '10/10min',
        'auth.verify_email': '10/hour',
        'auth.check_username': '30/min',
        'content.post_create': '30/min',
        'content.reel_create': '20/min',
        'content.draft_write': '60/min',
        'content.scheduled_create': '30/min',
        'anon.read': '100/min',
        'anon.share': '30/min',
        'user.follow': '60/min',
        'user.like': '120/min',
        'user.comment': '30/min',
        'user.bookmark': '60/min',
        'user.report': '10/min',
        'search.query': '30/min',
        'search.autocomplete': '60/min',
    },
}

ENABLE_HTTPS_SECURITY = os.environ.get(
    'DJANGO_ENABLE_HTTPS_SECURITY', 'False'
).lower() in ('true', '1', 'yes')
SECURE_SSL_REDIRECT = ENABLE_HTTPS_SECURITY
SESSION_COOKIE_SECURE = ENABLE_HTTPS_SECURITY
CSRF_COOKIE_SECURE = ENABLE_HTTPS_SECURITY
SECURE_HSTS_SECONDS = int(
    os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000' if ENABLE_HTTPS_SECURITY else '0')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = ENABLE_HTTPS_SECURITY
SECURE_HSTS_PRELOAD = ENABLE_HTTPS_SECURITY
SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https') if ENABLE_HTTPS_SECURITY else None
)

AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '').strip()
USE_S3_MEDIA_STORAGE = bool(AWS_STORAGE_BUCKET_NAME)
if USE_S3_MEDIA_STORAGE:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '').strip() or None
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '').strip() or (
        f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    )
    AWS_DEFAULT_ACL = None
    # Bucket keeps Block Public Access on (deliberate) — every media URL must be
    # a signed, time-limited GET rather than assuming public-read.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3.S3Storage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }

_CDN_URL = os.environ.get('CDN_URL', '').rstrip('/')
if _CDN_URL:
    MEDIA_URL = f'{_CDN_URL}/media/'
    STATIC_URL = f'{_CDN_URL}/static/'
elif USE_S3_MEDIA_STORAGE:
    MEDIA_URL = os.environ.get('DJANGO_MEDIA_URL', '').strip() or f'https://{AWS_S3_CUSTOM_DOMAIN}/'
else:
    MEDIA_URL = os.environ.get('DJANGO_MEDIA_URL', '/media/')
    # STATIC_URL already set above; preserve the env-driven value.
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or '587')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() in ('true', '1', 'yes')
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@outverse.local')

# AI moderation (optional — soft-flag by default when keys present)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
NVIDIA_API_KEY = os.environ.get('NVIDIA_API_KEY', '')
AI_MODERATION_HARD_BLOCK = os.environ.get('AI_MODERATION_HARD_BLOCK', '0') == '1'

# Cosmic Pass (Stripe). Empty by default — checkout is disabled until real keys are set.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000').rstrip('/')

# Optional — Cloudflare Stream Live Inputs (real RTMP/WHIP + HLS).
CLOUDFLARE_STREAM_ACCOUNT_ID = os.environ.get('CLOUDFLARE_STREAM_ACCOUNT_ID', '')
CLOUDFLARE_STREAM_API_TOKEN = os.environ.get('CLOUDFLARE_STREAM_API_TOKEN', '')
CLOUDFLARE_STREAM_CUSTOMER_CODE = os.environ.get('CLOUDFLARE_STREAM_CUSTOMER_CODE', '')

# Ads pricing (USD per 1000 impressions / per click)
ADS_CPM_RATE = float(os.environ.get('ADS_CPM_RATE', '5.0'))
ADS_CPC_RATE = float(os.environ.get('ADS_CPC_RATE', '0.50'))

# Web Push (PWA). Generate VAPID keys with: python scripts/generate_vapid_env.py
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
_raw_vapid_private = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_PRIVATE_KEY = _raw_vapid_private.replace('\\n', '\n') if _raw_vapid_private else ''
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:admin@outverse.local')
